apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: LoadBalancer
  selector:
    app: vproapp
  ports:
    - protocol: TCP
      port: 80 # default http port
      targetPort: vproapp-port